version: '3'

services:
  mysql:
    container_name: "mysql"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testedb"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
